name: Demo11 # name can be anything  # Optional
run-name: ${{ github.actor }} is learning Github Actions  # Optional

on:
  push:
    branches:
      - main
    paths:
      - 'src/**' # ** means wildcard to match child folders or files
  pull_request:
    branches: '*' #all branches or [develop] # or main
    paths:
      - 'src/**'

jobs:
  first-job: # job name can be anything test, build, deploy, release, etc
    runs-on: ubuntu-latest #or windows-latest

    steps:
      - run: echo $Full_Name
        env:
            Full_Name: "Soufiane Saadouni"
